import json
from typing import Any

from openai import OpenAI

from .config import OPENAI_API_KEY, OPENAI_MODEL
from .utils import setup_logger


logger = setup_logger(__name__)

VALID_RESPONSE_FORMATS: list[str] = ["text", "json"]


def validate_openai_api_key() -> None:
    """
    Validate that the OpenAI API key is configured.

    Raises:
        ValueError: If OPENAI_API_KEY is not configured.
    """
    logger.info("Validating OpenAI API key configuration.")

    if not OPENAI_API_KEY:
        raise ValueError("OPENAI_API_KEY is not configured.")


def create_openai_client() -> OpenAI:
    """
    Create an OpenAI client using the configured API key.

    Returns:
        OpenAI client instance.

    Raises:
        ValueError: If OPENAI_API_KEY is not configured.
    """
    logger.info("Creating OpenAI client.")

    validate_openai_api_key()
    return OpenAI(api_key=OPENAI_API_KEY)


def build_analysis_messages(payload: dict[str, Any]) -> list[dict[str, str]]:
    """
    Build OpenAI chat messages for executive education analysis.

    Args:
        payload: Analytical payload generated by the pipeline.

    Returns:
        List of messages compatible with the OpenAI Chat Completions API.

    Raises:
        TypeError: If payload is not a dictionary.
    """
    logger.info("Building executive analysis messages.")

    if not isinstance(payload, dict):
        raise TypeError("payload must be a dictionary.")

    payload_json = json.dumps(
        payload,
        ensure_ascii=False,
        indent=2,
        default=str,
    )

    system_message = (
        "Você é um analista executivo global de educação. "
        "Sua função é interpretar dados educacionais processados do World Bank "
        "Education Statistics EdStats e gerar uma análise clara, objetiva e "
        "estruturada em português brasileiro. "
        "Baseie-se exclusivamente no payload recebido. "
        "Não invente dados. "
        "Quando os dados forem insuficientes, informe explicitamente essa limitação. "
        "Não realize cálculos complexos; apenas interprete os dados fornecidos."
    )

    user_message = (
        "Analise o payload educacional abaixo e gere uma análise executiva contendo:\n"
        "1. resumo executivo;\n"
        "2. países em evolução;\n"
        "3. países estagnados ou em queda;\n"
        "4. rankings relevantes;\n"
        "5. padrões observados;\n"
        "6. alertas;\n"
        "7. recomendações;\n"
        "8. limitações dos dados.\n\n"
        "Payload:\n"
        f"{payload_json}"
    )

    return [
        {"role": "system", "content": system_message},
        {"role": "user", "content": user_message},
    ]


def generate_executive_analysis(
    payload: dict[str, Any],
    response_format: str = "text",
) -> str | dict[str, Any]:
    """
    Generate an executive education analysis using OpenAI.

    Args:
        payload: Analytical payload generated by the pipeline.
        response_format: Expected return format. Accepted values are "text" and "json".

    Returns:
        Analysis as a string or dictionary.

    Raises:
        TypeError: If payload or response_format has an invalid type.
        ValueError: If response_format is invalid or JSON parsing fails.
        json.JSONDecodeError: If JSON decoding fails.
        Exception: For OpenAI SDK or unexpected errors.
    """
    logger.info("Starting OpenAI executive analysis generation.")

    try:
        if not isinstance(payload, dict):
            raise TypeError("payload must be a dictionary.")

        if not isinstance(response_format, str):
            raise TypeError("response_format must be a string.")

        if response_format not in VALID_RESPONSE_FORMATS:
            raise ValueError(
                f"Invalid response_format '{response_format}'. "
                f"Valid options are: {VALID_RESPONSE_FORMATS}"
            )

        messages = build_analysis_messages(payload)
        client = create_openai_client()

        logger.info("Calling OpenAI model: %s", OPENAI_MODEL)

        response = client.chat.completions.create(
            model=OPENAI_MODEL,
            messages=messages,
            temperature=0.2,
        )

        content = response.choices[0].message.content

        if content is None:
            raise ValueError("OpenAI returned an empty response.")

        logger.info("OpenAI executive analysis generated successfully.")

        if response_format == "json":
            try:
                return json.loads(content)
            except json.JSONDecodeError:
                logger.exception("OpenAI response is not valid JSON.")
                raise ValueError("OpenAI response is not valid JSON.") from None

        return content

    except TypeError:
        logger.exception("Invalid input type during OpenAI analysis generation.")
        raise
    except ValueError:
        logger.exception("Invalid value during OpenAI analysis generation.")
        raise
    except json.JSONDecodeError:
        logger.exception("Failed to decode OpenAI response as JSON.")
        raise
    except Exception:
        logger.exception("Unexpected error during OpenAI analysis generation.")
        raise