from typing import Any

import pandas as pd

from .utils import setup_logger


logger = setup_logger(__name__)

SECTION_EXECUTIVE_SUMMARY = "Resumo Executivo"
SECTION_MAIN_INDICATORS = "Principais Indicadores"
SECTION_RANKINGS = "Rankings"
SECTION_COMPARISONS = "Comparação entre Países"
SECTION_TRENDS = "Tendências Observadas"
SECTION_ALERTS = "Alertas"
SECTION_RECOMMENDATIONS = "Recomendações"
SECTION_LIMITATIONS = "Limitações dos Dados"


def _validate_dataframe(df: pd.DataFrame, name: str) -> None:
    """
    Validate that an object is a pandas DataFrame.

    Args:
        df: Object to validate.
        name: Name used in error messages.

    Raises:
        TypeError: If df is not a pandas DataFrame.
    """
    if not isinstance(df, pd.DataFrame):
        raise TypeError(f"{name} must be a pandas DataFrame.")


def _validate_max_rows(max_rows: int) -> None:
    """
    Validate that max_rows is a positive integer.

    Args:
        max_rows: Maximum number of rows.

    Raises:
        TypeError: If max_rows is not an integer.
        ValueError: If max_rows is not positive.
    """
    if not isinstance(max_rows, int):
        raise TypeError("max_rows must be an integer.")

    if max_rows <= 0:
        raise ValueError("max_rows must be a positive integer.")


def _dataframe_to_records(
    df: pd.DataFrame,
    max_rows: int | None = None,
) -> list[dict[str, Any]]:
    """
    Convert a DataFrame to records.

    Args:
        df: DataFrame to convert.
        max_rows: Optional maximum number of rows.

    Returns:
        List of dictionary records.
    """
    if df.empty:
        return []

    output_df = df.copy()

    if max_rows is not None:
        output_df = output_df.head(max_rows)

    return output_df.to_dict(orient="records")


def _dataframe_to_markdown_table(
    df: pd.DataFrame,
    empty_message: str,
    max_rows: int | None = 10,
) -> str:
    """
    Convert a DataFrame to a Markdown table with fallback.

    Args:
        df: DataFrame to convert.
        empty_message: Message returned when the DataFrame is empty.
        max_rows: Optional maximum number of rows.

    Returns:
        Markdown table or fallback plain text table.
    """
    if df.empty:
        return empty_message

    output_df = df.copy()

    if max_rows is not None:
        output_df = output_df.head(max_rows)

    try:
        return output_df.to_markdown(index=False)
    except ImportError:
        return output_df.to_string(index=False)


def build_structured_report(
    metrics_df: pd.DataFrame,
    rankings_df: pd.DataFrame,
    comparisons_df: pd.DataFrame,
    openai_analysis: str,
    max_rows: int = 10,
) -> dict[str, Any]:
    """
    Build a structured executive report as a dictionary.

    Args:
        metrics_df: DataFrame containing analytical metrics.
        rankings_df: DataFrame containing rankings.
        comparisons_df: DataFrame containing country comparisons.
        openai_analysis: Executive analysis generated by OpenAI.
        max_rows: Maximum rows included from each DataFrame.

    Returns:
        Structured report dictionary.

    Raises:
        TypeError: If inputs have invalid types.
        ValueError: If max_rows is invalid.
        Exception: For unexpected errors.
    """
    logger.info("Starting structured report generation.")

    try:
        _validate_dataframe(metrics_df, "metrics_df")
        _validate_dataframe(rankings_df, "rankings_df")
        _validate_dataframe(comparisons_df, "comparisons_df")

        if not isinstance(openai_analysis, str):
            raise TypeError("openai_analysis must be a string.")

        _validate_max_rows(max_rows)

        logger.info("metrics_df shape: %s", metrics_df.shape)
        logger.info("rankings_df shape: %s", rankings_df.shape)
        logger.info("comparisons_df shape: %s", comparisons_df.shape)

        alerts: list[str] = []

        if metrics_df.empty:
            alerts.append("O DataFrame de métricas está vazio.")

        if rankings_df.empty:
            alerts.append("O DataFrame de rankings está vazio.")

        if comparisons_df.empty:
            alerts.append("O DataFrame de comparações está vazio.")

        trends_summary: dict[str, int] = {}

        if "trend" in metrics_df.columns and not metrics_df.empty:
            trends_summary = (
                metrics_df["trend"]
                .dropna()
                .astype(str)
                .value_counts()
                .to_dict()
            )

        report = {
            "resumo_executivo": openai_analysis,
            "principais_indicadores": _dataframe_to_records(metrics_df, max_rows),
            "rankings": _dataframe_to_records(rankings_df, max_rows),
            "comparacao_entre_paises": _dataframe_to_records(
                comparisons_df,
                max_rows,
            ),
            "tendencias_observadas": trends_summary,
            "alertas": alerts,
            "recomendacoes": [
                "Priorizar análise dos indicadores com maior variação entre países.",
                "Investigar países com tendência de queda ou estabilidade prolongada.",
                "Combinar rankings com contexto socioeconômico antes de tomar decisões.",
            ],
            "limitacoes_dos_dados": [
                "Podem existir valores ausentes nos indicadores analisados.",
                "A cobertura temporal pode variar entre países e indicadores.",
                "Os resultados dependem da qualidade e atualização dos dados de origem.",
            ],
        }

        logger.info("Structured report generated successfully.")
        return report

    except TypeError:
        logger.exception("Invalid input type during structured report generation.")
        raise
    except ValueError:
        logger.exception("Invalid value during structured report generation.")
        raise
    except Exception:
        logger.exception("Unexpected error during structured report generation.")
        raise


def build_markdown_report(
    metrics_df: pd.DataFrame,
    rankings_df: pd.DataFrame,
    comparisons_df: pd.DataFrame,
    openai_analysis: str,
    max_rows: int = 10,
) -> str:
    """
    Build an executive report in Markdown format.

    Args:
        metrics_df: DataFrame containing analytical metrics.
        rankings_df: DataFrame containing rankings.
        comparisons_df: DataFrame containing country comparisons.
        openai_analysis: Executive analysis generated by OpenAI.
        max_rows: Maximum rows included from each DataFrame.

    Returns:
        Markdown report string.

    Raises:
        TypeError: If inputs have invalid types.
        ValueError: If max_rows is invalid.
        Exception: For unexpected errors.
    """
    logger.info("Starting Markdown report generation.")

    try:
        _validate_dataframe(metrics_df, "metrics_df")
        _validate_dataframe(rankings_df, "rankings_df")
        _validate_dataframe(comparisons_df, "comparisons_df")

        if not isinstance(openai_analysis, str):
            raise TypeError("openai_analysis must be a string.")

        _validate_max_rows(max_rows)

        logger.info("metrics_df shape: %s", metrics_df.shape)
        logger.info("rankings_df shape: %s", rankings_df.shape)
        logger.info("comparisons_df shape: %s", comparisons_df.shape)

        trends_summary = "Nenhuma tendência disponível."

        if "trend" in metrics_df.columns and not metrics_df.empty:
            trend_counts = (
                metrics_df["trend"]
                .dropna()
                .astype(str)
                .value_counts()
                .to_dict()
            )

            if trend_counts:
                trends_summary = "\n".join(
                    f"- {trend}: {count}" for trend, count in trend_counts.items()
                )

        alerts: list[str] = []

        if metrics_df.empty:
            alerts.append("- O DataFrame de métricas está vazio.")

        if rankings_df.empty:
            alerts.append("- O DataFrame de rankings está vazio.")

        if comparisons_df.empty:
            alerts.append("- O DataFrame de comparações está vazio.")

        alerts_text = "\n".join(alerts) if alerts else "- Nenhum alerta crítico identificado."

        metrics_table = _dataframe_to_markdown_table(
            metrics_df,
            "Não há métricas disponíveis para exibição.",
            max_rows=max_rows,
        )

        rankings_table = _dataframe_to_markdown_table(
            rankings_df,
            "Não há rankings disponíveis para exibição.",
            max_rows=max_rows,
        )

        comparisons_table = _dataframe_to_markdown_table(
            comparisons_df,
            "Não há comparações disponíveis para exibição.",
            max_rows=max_rows,
        )

        markdown_report = f"""# Relatório Executivo — Educação Global

## {SECTION_EXECUTIVE_SUMMARY}

{openai_analysis}

## {SECTION_MAIN_INDICATORS}

{metrics_table}

## {SECTION_RANKINGS}

{rankings_table}

## {SECTION_COMPARISONS}

{comparisons_table}

## {SECTION_TRENDS}

{trends_summary}

## {SECTION_ALERTS}

{alerts_text}

## {SECTION_RECOMMENDATIONS}

- Priorizar análise dos indicadores com maior variação entre países.
- Investigar países com tendência de queda ou estabilidade prolongada.
- Combinar rankings com contexto socioeconômico antes de tomar decisões.

## {SECTION_LIMITATIONS}

- Podem existir valores ausentes nos indicadores analisados.
- A cobertura temporal pode variar entre países e indicadores.
- Os resultados dependem da qualidade e atualização dos dados de origem.
"""

        logger.info("Markdown report generated successfully.")
        return markdown_report

    except TypeError:
        logger.exception("Invalid input type during Markdown report generation.")
        raise
    except ValueError:
        logger.exception("Invalid value during Markdown report generation.")
        raise
    except Exception:
        logger.exception("Unexpected error during Markdown report generation.")
        raise